# Generated by Django 4.0.5 on 2022-06-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='cputemp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
