# Generated by Django 4.0.5 on 2022-06-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_sensordata_cputemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='altitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
